name: jonigirvanphotography
favicon: null
layout_spectrum: 0.24021
typography_spectrum: 0.56875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00bbb6'
    - '#ffcf43'
    - '#a5a6aa'
    - '#c6c7c9'
  brandStrength: 0.75
  lightness: 0.4375
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
